name: Scrape and Analyze Daily

on:
  schedule:
    # Runs at 02:30 UTC and 14:30 UTC every day
    - cron: '30 2 * * *'
    - cron: '30 14 * * *'
  # Allows you to run the entire workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # ===================================================================
  # JOB 1: Scrapes data every day
  # ===================================================================
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the scraper
      run: python scraper.py

    - name: Validate Scraper Output
      id: validate_output
      run: |
        if [[ -z "$(git status --porcelain)" && "${{ github.event_name }}" == "schedule" ]]; then
          echo "::error::No new data was scraped on a scheduled run. This indicates a potential silent failure. Check the scraper and the target website."
          exit 1
        else
          echo "Scraper output validated. New data was found, or the workflow was triggered manually."
        fi

    - name: Commit and push scraped data
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions-bot@github.com"
        git add data/
        git diff --staged --quiet || git commit -m "Chore: Update scraped data"
        git push

    - name: Upload data artifact
      uses: actions/upload-artifact@v4
      with:
        name: scraped-data
        path: data/
    
  # ===================================================================
  # JOB 2: Runs analysis and updates README every day
  # ===================================================================
  analyze:
    needs: scrape
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Download data artifact
      uses: actions/download-artifact@v4
      with:
        name: scraped-data
        path: data/

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download NLTK data
      run: python -m nltk.downloader stopwords vader_lexicon

    - name: Run the analyzer script
      run: python analysis/topic_modelling_analysis.py

    - name: Update README with latest analysis
      run: python update_readme.py

    - name: Commit and push analysis report and README
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions-bot@github.com"
        
        # Add all relevant generated files to the staging area
        git add analysis/analysis_reports.json data/ README.md
        
        # Check if there are any changes to commit. If not, the script exits successfully.
        if git diff --staged --quiet; then
          echo "No changes to analysis report or README. Skipping commit."
        else
          # If there are changes, commit and push them.
          git commit -m "Feat: Generate daily analysis report and update README"
          
          # Pull changes from the 'scrape' job's push before pushing our own commit
          git pull --rebase
          
          git push
        fi
