name: Scrape Daily, Analyze Weekly

on:
  schedule:
    # Runs at 05:00 UTC every day.
    - cron: '0 5 * * *'
  # Allows you to run the entire workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # ===================================================================
  # JOB 1: Scrapes data every day
  # ===================================================================
  scrape:
    runs-on: ubuntu-latest
    outputs:
      is_analysis_day: ${{ steps.check_day.outputs.is_analysis_day }}

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the scraper
      run: python scraper.py

    - name: Validate Scraper Output
      id: validate_output
      run: |
        if [[ -z "$(git status --porcelain)" && "${{ github.event_name }}" == "schedule" ]]; then
          echo "::error::No new data was scraped on a scheduled run. This indicates a potential silent failure. Check the scraper and the target website."
          exit 1
        else
          echo "Scraper output validated. New data was found, or the workflow was triggered manually."
        fi

    - name: Commit and push scraped data
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions-bot@github.com"
        git add data/statuses.json
        git diff --staged --quiet || git commit -m "Chore: Update scraped data"
        git push

    # <-- FIX HERE -->
    - name: Upload data artifact
      uses: actions/upload-artifact@v4  # Changed from v3 to v4
      with:
        name: scraped-data
        path: data/

    - name: Check if today is analysis day (Sunday)
      id: check_day
      run: |
        if [ $(date -u +%u) -eq 7 ]; then
          echo "is_analysis_day=true" >> $GITHUB_OUTPUT
        else
          echo "is_analysis_day=false" >> $GITHUB_OUTPUT
        fi

  # ===================================================================
  # JOB 2: Runs analysis only on the scheduled day or on manual trigger
  # ===================================================================
  analyze:
    needs: scrape
    if: needs.scrape.outputs.is_analysis_day == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    # <-- FIX HERE -->
    - name: Download data artifact
      uses: actions/download-artifact@v4 # Changed from v3 to v4
      with:
        name: scraped-data
        path: data/

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download NLTK data
      run: python -m nltk.downloader stopwords wordnet averaged_perceptron_tagger

    - name: Run the analyzer script
      run: python analysis/topic_modelling_analysis.py

    - name: Commit and push analysis report
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions-bot@github.com"

        if [ -f "analysis/analysis_reports.json" ]; then
          echo "Analysis report found. Committing changes."
          # Add both the report and the data it was based on for consistency
          git add analysis/analysis_reports.json data/statuses.json
          git diff --staged --quiet || git commit -m "Feat: Generate weekly analysis report"
          
          # Pull the scraper's commit before pushing our own
          git pull --rebase
          
          git push
        else
          echo "No analysis report generated. Skipping commit."
        fi
